= Basic authentication policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-basic-authentication/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-basic-authentication/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===

== Description

You can use the `basic-authentication` policy to manage basic authentication headers sent in API calls. The policy compares the user and password sent in the basic authentication header to an APIM user to determine if the user credentials are valid.

To use the policy in an API, you need to:

* configure an LDAP or inline resource for your API plan, which specifies where the APIM users are stored
* configure a basic authentication policy for the API flows

NOTE: LDAP and inline resources are not part of the default APIM configuration, so you must configure an LDAP or inline resource for APIM first, as described in the link:/apim/3.x/apim_devguide_plugins.html[Developer Guide^].

=== Policy identifier

You can enable or disable the policy with policy identifier `policy-basic-authentication`.

== Configuration

The policy configuration is as follows:

|===
|Property |Description |Type

|authenticationProviders||List of strings
|realm||string
